services:
    laravel.test:
        build:
            context: './docker/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - redis
            - mailpit
            - otel-collector
    pgsql:
        image: 'postgres:17-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './docker/pgsql:/docker-entrypoint-initdb.d'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    otel-collector:
        image: 'newrelic/nr-otel-collector:0.8.10'
        environment:
            NEW_RELIC_LICENSE_KEY: '${NEW_RELIC_LICENSE_KEY}'
            NEW_RELIC_REGION: '${NEW_RELIC_REGION:-us}'
            NEW_RELIC_MEMORY_LIMIT_MIB: '${NEW_RELIC_MEMORY_LIMIT_MIB:-512}'
            NEW_RELIC_OTLP_BASE_ENDPOINT: '${NEW_RELIC_OTLP_BASE_ENDPOINT:-https://otlp.nr-data.net}'
            NEW_RELIC_TRACES_ENDPOINT: '${NEW_RELIC_TRACES_ENDPOINT:-https://otlp.nr-data.net/v1/traces}'
            NEW_RELIC_METRICS_ENDPOINT: '${NEW_RELIC_METRICS_ENDPOINT:-https://otlp.nr-data.net/v1/metrics}'
            NEW_RELIC_LOGS_ENDPOINT: '${NEW_RELIC_LOGS_ENDPOINT:-https://otlp.nr-data.net/v1/logs}'
        volumes:
            - './docker/otel-collector/config.yaml:/etc/newrelic-otel-collector/config.yaml:ro'
        ports:
            - '${FORWARD_OTEL_HTTP_PORT:-4318}:4318'
            - '${FORWARD_OTEL_GRPC_PORT:-4317}:4317'
        command: ['--config=/etc/newrelic-otel-collector/config.yaml']
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
