receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch: {}

exporters:
  otlphttp/newrelic:
    endpoint: ${NEW_RELIC_OTLP_BASE_ENDPOINT}
    traces_endpoint: ${NEW_RELIC_TRACES_ENDPOINT}
    metrics_endpoint: ${NEW_RELIC_METRICS_ENDPOINT}
    logs_endpoint: ${NEW_RELIC_LOGS_ENDPOINT}
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}
    compression: gzip
    retry_on_failure:
      enabled: true
    sending_queue:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/newrelic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/newrelic]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/newrelic]
